services:
  wa-dashboard:
    image: ghcr.io/bipprojectbali/wa-dashboard:stg-latest
    container_name: wa-dashboard-stg
    restart: unless-stopped
    networks:
      - public-net
      - postgres-net-stg
      - redis-net
    mem_limit: 512m
    cpus: '1.0'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public-net"
      - "traefik.http.routers.wa-dashboard.rule=Host(`wa-dashboard.wibudev.com`)"
      - "traefik.http.routers.wa-dashboard.entrypoints=websecure"
      - "traefik.http.routers.wa-dashboard.tls=true"
      - "traefik.http.routers.wa-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.wa-dashboard.loadbalancer.server.port=3000"

networks:
  public-net:
    external: true
  postgres-net-stg:
    external: true
  redis-net:
    external: true
