services:
  wa-dashboard:
    image: ghcr.io/bipprojectbali/wa-dashboard:stg-latest
    container_name: wa-dashboard-stg
    restart: unless-stopped
    networks:
      - public-net
      - postgres-net-stg
      - redis-net
    mem_limit: 512m
    cpus: '1.0'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public-net"
      - "traefik.http.routers.wa-dashboard.rule=Host(`wa-dashboard.wibudev.com`)"
      - "traefik.http.routers.wa-dashboard.entrypoints=websecure"
      - "traefik.http.routers.wa-dashboard.tls=true"
      - "traefik.http.routers.wa-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.wa-dashboard.loadbalancer.server.port=3000"
    environment:
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - GH_REPO=${GH_REPO}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - HMR_PORT=${HMR_PORT}
      - MCP_SECRET=${MCP_SECRET}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
      - STACK_NAME=${STACK_NAME}
      - STG_BASE_URL=${STG_BASE_URL}
      - STG_STACK_NAME=${STG_STACK_NAME}
      - SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL}
      - TELEGRAM_NOTIFY_CHAT_ID=${TELEGRAM_NOTIFY_CHAT_ID}
      - TELEGRAM_NOTIFY_TOKEN=${TELEGRAM_NOTIFY_TOKEN}
      - WA_API_BASE_URL=${WA_API_BASE_URL}
      - WA_API_KEY=${WA_API_KEY}
      - WA_VERIFY_SERVER_NUMBER=${WA_VERIFY_SERVER_NUMBER}


networks:
  public-net:
    external: true
  postgres-net-stg:
    external: true
  redis-net:
    external: true