import { Elysia, t } from 'elysia'
import { appLog } from '../lib/applog'
import { betterAuthPlugin } from '../lib/auth-middleware'
import { prisma } from '../lib/db'
import { audit, getIp, guardAdmin, guardSuperAdmin } from '../lib/route-helpers'
import { generateApiKey, generateWebhookSecret } from '../lib/wa-verify-keys'

// Management consumer WAV (auth: session cookie). Baca: ADMIN+. Tulis: SUPER_ADMIN.
// API key plaintext HANYA dikembalikan sekali (saat create / regenerate) — tak disimpan.
// Inspeksi request/inbound/replay ada di wa.verify.logs.ts (pisah demi file-health).

const consumerBody = t.Object({
  name: t.String({ minLength: 1, maxLength: 100 }),
  webhookUrl: t.Optional(t.Union([t.String({ maxLength: 500 }), t.Null()])),
  active: t.Optional(t.Boolean()),
})

export const waVerifyAdminRouter = new Elysia({ tags: ['WA Verify'] })
  .use(betterAuthPlugin)

  .get(
    '/api/wa/verify/consumers',
    async ({ authUser }) => {
      const guard = guardAdmin(authUser)
      if (guard) return guard
      const consumers = await prisma.verifyConsumer.findMany({
        select: {
          id: true,
          name: true,
          apiKeyPrefix: true,
          webhookUrl: true,
          active: true,
          createdAt: true,
          _count: { select: { requests: true } },
        },
        orderBy: { createdAt: 'desc' },
        take: 200,
      })
      return { consumers, canEdit: authUser!.role === 'SUPER_ADMIN' }
    },
    { detail: { summary: 'List verify consumers', security: [{ cookieAuth: [] }] } },
  )

  .post(
    '/api/wa/verify/consumers',
    async ({ authUser, body, request }) => {
      const guard = guardSuperAdmin(authUser)
      if (guard) return guard
      const key = generateApiKey()
      const consumer = await prisma.verifyConsumer.create({
        data: {
          name: body.name,
          apiKeyHash: key.hash,
          apiKeyPrefix: key.prefix,
          webhookUrl: body.webhookUrl ?? null,
          webhookSecret: generateWebhookSecret(),
          active: body.active ?? true,
          createdById: authUser!.id,
        },
        select: { id: true, name: true, apiKeyPrefix: true, webhookSecret: true },
      })
      audit(authUser!.id, 'WA_VERIFY_CONSUMER_CREATED', `id=${consumer.id} name=${body.name}`, getIp(request))
      appLog('info', `WA verify consumer created by ${authUser!.email}`, `id=${consumer.id}`)
      return { consumer, apiKey: key.plaintext }
    },
    { detail: { summary: 'Create verify consumer (SUPER_ADMIN)', security: [{ cookieAuth: [] }] }, body: consumerBody },
  )

  .put(
    '/api/wa/verify/consumers/:id',
    async ({ authUser, params, body, request }) => {
      const guard = guardSuperAdmin(authUser)
      if (guard) return guard
      const consumer = await prisma.verifyConsumer
        .update({
          where: { id: params.id },
          data: { name: body.name, webhookUrl: body.webhookUrl ?? null, active: body.active ?? undefined },
          select: { id: true, name: true, webhookUrl: true, active: true },
        })
        .catch(() => null)
      if (!consumer) return new Response(JSON.stringify({ error: 'Consumer tidak ditemukan.' }), { status: 404 })
      audit(authUser!.id, 'WA_VERIFY_CONSUMER_UPDATED', `id=${params.id}`, getIp(request))
      return { consumer }
    },
    { detail: { summary: 'Update verify consumer (SUPER_ADMIN)', security: [{ cookieAuth: [] }] }, body: consumerBody },
  )

  .post(
    '/api/wa/verify/consumers/:id/regenerate-key',
    async ({ authUser, params, request }) => {
      const guard = guardSuperAdmin(authUser)
      if (guard) return guard
      const key = generateApiKey()
      const consumer = await prisma.verifyConsumer
        .update({
          where: { id: params.id },
          data: { apiKeyHash: key.hash, apiKeyPrefix: key.prefix },
          select: { id: true },
        })
        .catch(() => null)
      if (!consumer) return new Response(JSON.stringify({ error: 'Consumer tidak ditemukan.' }), { status: 404 })
      audit(authUser!.id, 'WA_VERIFY_KEY_REGENERATED', `id=${params.id}`, getIp(request))
      appLog('info', `WA verify key regenerated by ${authUser!.email}`, `id=${params.id}`)
      return { apiKey: key.plaintext }
    },
    { detail: { summary: 'Regenerate consumer API key (SUPER_ADMIN)', security: [{ cookieAuth: [] }] } },
  )

  .delete(
    '/api/wa/verify/consumers/:id',
    async ({ authUser, params, request }) => {
      const guard = guardSuperAdmin(authUser)
      if (guard) return guard
      // deleteMany → idempoten & tak melempar saat 0 baris (count=0 ⇒ 404), tanpa noise prisma:error.
      const { count } = await prisma.verifyConsumer.deleteMany({ where: { id: params.id } })
      if (count === 0) return new Response(JSON.stringify({ error: 'Consumer tidak ditemukan.' }), { status: 404 })
      audit(authUser!.id, 'WA_VERIFY_CONSUMER_DELETED', `id=${params.id}`, getIp(request))
      return { ok: true }
    },
    { detail: { summary: 'Delete verify consumer (SUPER_ADMIN)', security: [{ cookieAuth: [] }] } },
  )
